server.port: 9000
management.server.port: 9001
management.server.address: 127.0.0.1
server.error.whitelabel.enabled: false
spring.mvc.throw-exception-if-no-handler-found: true
#spring.resources.add-mappings: false
